### ISSUE TITLE
Error on skipping Nessus Install

### ISSUE THREAD

**Issue by jreynders** [TUVOpenSky-THREATS/KaliVirtualDropbox#6]
When a user presses Return to skip installing Nessus, the script still attempts to install Nessus:

![2018-09-24 09_48_03](https://user-images.githubusercontent.com/6164800/45964203-a5e61b80-c014-11e8-90fa-8d53c2228df4.png)

**Comment by sethsec** [comment]
Nice!  Thanks.  Ill update this shortly.  looks like I missed a $
